-- MySQL Script generated by MySQL Workbench
-- Fri Dec 13 09:29:33 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id_usuario` BINARY(16) NOT NULL DEFAULT UUID_TO_BIN(uuid()),
  `nombre_usuario` VARCHAR(50) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `contrasenia` VARCHAR(32) NOT NULL,
  `creado_en` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `usuarioscol_UNIQUE` (`nombre_usuario` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`listas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`listas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`listas` (
  `id_lista` BINARY(16) NOT NULL DEFAULT UUID_TO_BIN(uuid()),
  `nombre_lista` VARCHAR(100) NOT NULL,
  `creado_en` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_lista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios_listas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuarios_listas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuarios_listas` (
  `id_usuario` BINARY(16) NOT NULL,
  `id_lista` BINARY(16) NOT NULL,
  PRIMARY KEY (`id_usuario`, `id_lista`),
  INDEX `fk_listas_idx` (`id_lista` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`usuarios` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_listas`
    FOREIGN KEY (`id_lista`)
    REFERENCES `mydb`.`listas` (`id_lista`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`items` ;

CREATE TABLE IF NOT EXISTS `mydb`.`items` (
  `id_item` BINARY(16) NOT NULL DEFAULT UUID_TO_BIN(uuid()),
  `id_lista` BINARY(16) NOT NULL,
  `texto_item` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_item`),
  INDEX `fk_items_lista_idx` (`id_lista` ASC) VISIBLE,
  CONSTRAINT `fk_items_lista`
    FOREIGN KEY (`id_lista`)
    REFERENCES `mydb`.`listas` (`id_lista`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
